# NumPy Beginner Tutorial – Session 1

In [214]:
import numpy as np

## create 1D array, Vector, matrix (2D array) and Tensor (3 and more dimension array)

In [215]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

## Shape, size and ndim

In [216]:
print(arr2D.shape)  # This will show (2,3) meaning matrix (2D or more dimension array)
print(arr2D.size)  # This will show 6 meaning total 6 elements
print(arr2D.ndim)  # This will show 2 meaning 2 dimension

(2, 3)
6
2


In [217]:
arr1D = np.arange(1, 10, 0.5)
arr1D

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

### Difference Between 1D Array and Vector (2D array with 1xm or nx1) and 2D Array (Matrix)

In [218]:
print(arr1D.shape)  # This will show (18,) meaning vector (1D array) with 18 elements
print(arr1D.size)  # This will show 18 meaning total 18 elements
print(arr1D.ndim)  # This will show 1 meaning 1 dimension

(18,)
18
1


### But for better understanding let's see the difference between 1D array (vector) and 2D array (matrix)

In [219]:
arr02D = arr1D.reshape(1, 18)  # 1 row, 18 columns
print(
    arr02D.shape
)  # This will show (1,18) meaning matrix (2D array) with 1 row and 18 columns
print(arr02D.size)  # This will show 18 meaning total 18 elements
print(arr02D.ndim)  # This will show 2 meaning 2 dimension

(1, 18)
18
2


### Or

In [220]:
arr002D = arr1D.reshape(18, 1)  # 18 rows, 1 column
print(
    arr002D.shape
)  # This will show (18,1) meaning matrix (2D array) with 18 rows and 1 column
print(arr002D.size)  # This will show 18 meaning total 18 elements
print(arr002D.ndim)  # This will show 2 meaning 2 dimension

(18, 1)
18
2


## Matrix

In [221]:
arr0002D = arr1D.reshape(6, 3)  # 6 rows, 3 column
print(
    arr0002D.shape
)  # This will show (6,3) meaning matrix (2D array) with 6 rows and 3 column
print(arr0002D.size)  # This will show 18 meaning total 18 elements
print(arr0002D.ndim)  # This will show 2 meaning 2 dimension

(6, 3)
18
2


## Tensor

In [222]:
arr3D = arr1D.reshape(2, 3, 3)  # 2 rows, 3 column, 3 depth
print(
    arr3D.shape
)  # This will show (2,3,3) meaning tensor (3D array) with 2 rows, 3 column and 3 depth
print(arr3D.size)  # This will show 18 meaning total 18 elements
print(arr3D.ndim)  # This will show 3 meaning 3 dimension

(2, 3, 3)
18
3


In [223]:
arr4D = arr1D.reshape(2, 3, 3, 1)  # 2 rows, 3 column, 3 depth, 1 depth
print(
    arr4D.shape
)  # This will show (2,3,3,1) meaning tensor (4D array) with 2 rows, 3 column and 3 depth and 1 depth
print(arr4D.size)  # This will show 18 meaning total 18 elements
print(arr4D.ndim)  # This will show 4 meaning 4 dimension

(2, 3, 3, 1)
18
4


## Shape (:,-1)

In [224]:
arr03D = arr1D.reshape(2, 3, -1)  # 2 rows, 3 column, depth inferred
print(
    arr03D.shape
)  # This will show (2,3,3) meaning tensor (3D array) with 2 rows, 3 column and 3 depth
print(arr03D.size)  # This will show 18 meaning total 18 elements
print(arr03D.ndim)  # This will show 3 meaning 3 dimension

(2, 3, 3)
18
3


## concatenate((.), axis=Ax)

In [225]:
arr1 = np.arange(1, 10, 0.5)
arr2 = np.arange(10, 19, 0.5)
print(arr1.shape, arr2D.shape)
arr_concat1 = np.concatenate((arr1, arr2), axis=0)  # concatenate as 1D arrays
arr_concat01 = np.concatenate(
    (arr1.reshape(-1, 1), arr2.reshape(-1, 1)), axis=0
)  # concatenate as column vectors
arr_concat2 = np.concatenate(
    (arr1.reshape(-1, 1), arr2.reshape(-1, 1)), axis=1
)  # concatenate as row vectors
print(arr_concat1.shape, arr_concat01.shape, arr_concat2.shape)

(18,) (2, 3)
(36,) (36, 1) (18, 2)


In [226]:
arr_vertical = np.vstack((arr1.reshape(-1, 1), arr2.reshape(-1, 1)))  # vertical stack as column vectors (One below another)
arr_horizontal = np.hstack((arr1.reshape(-1, 1), arr2.reshape(-1, 1)))  # horizontal stack as row vectors (Beside each other)
print(arr_vertical.shape, arr_horizontal.shape)

(36, 1) (18, 2)


# Broadcasting in NumPy
### Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes in a way that makes sense mathematically.

In [227]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 5, 8])
arr3 = np.array([10])

### element-wise sum

In [228]:
arr_broadcast_sum1 = arr1 + arr2  # element-wise addition
arr_broadcast_sum1

array([ 4,  7, 11])

### broadcasting sum

In [229]:
arr_broadcast_sum2 = arr1 + arr3  # broadcasting addition
arr_broadcast_sum2

array([11, 12, 13])

## Sliced Arrays list_name[start_index:end_index:step] 

In [230]:
arr1 = np.arange(1, 10, 0.5)
arr2 = arr1[5:9]  # slicing from index 5 to 8
arr3 = arr1[::2]  # slicing every second element
arr4 = arr1[-5:]  # slicing last 5 elements
arr5 = arr1[-5::-1]  # slicing last 5 elements in reverse order
print(arr1, arr2, arr3, arr4, arr5, sep="\n")

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[3.5 4.  4.5 5. ]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[7.5 8.  8.5 9.  9.5]
[7.5 7.  6.5 6.  5.5 5.  4.5 4.  3.5 3.  2.5 2.  1.5 1. ]


## random numbers

In [231]:
rn = np.random.randn(
    3, 4
)  # generate random numbers from standard normal distribution in a 3x4 array
r = np.random.rand(
    3, 4
)  # generate random numbers from uniform distribution [0,1) in a 3x4 array
ri = np.random.randint(
    1, 10, size=(3, 4)
)  # generate random integers between 1 and 9 in a 3x4 array

In [232]:
rn_min = np.min(rn)  # minimum value in the array
rn_max = np.max(rn)  # maximum value in the array
rn_mean = np.mean(rn)  # mean value of the array
rn_median = np.median(rn)  # median value of the array
rn_var = np.var(rn)  # variance of the array
rn_std = np.std(
    rn
)  # standard deviation of the array (a_var**0.5  # square root of variance to get standard deviation)
print(rn, rn_min, rn_max, rn_mean, rn_median, rn_std, rn_var, sep="\n")

[[-1.14684361  0.05321626  1.1827419  -0.48443672]
 [ 1.4834781   1.12534856  0.43286956 -0.11057765]
 [ 1.10238056 -1.33273727 -0.06691798  0.39988253]]
-1.3327372652948402
1.4834781037441374
0.2198670208769443
0.2265493989319712
0.875313144420679
0.7661731007956164


In [233]:
rn_sorted = np.sort(rn)  # sorted array by rows (axis=-1)
rn_rows_sorted = np.sort(rn, axis=0)  # sorted array by columns
rn_columns_sorted = np.sort(rn, axis=1)  # sorted array by rows
rn_arg_sorted = np.argsort(rn)  # indices that would sort the array by rows (axis=-1)
rn_arg_rows_sorted = np.argsort(rn, axis=0)  # indices that would sort the array by columns
rn_arg_columns_sorted = np.argsort(rn, axis=1)  # indices that would sort the array by rows

print(rn, rn_sorted, rn_arg_sorted, rn_rows_sorted, rn_arg_rows_sorted, rn_columns_sorted, rn_arg_columns_sorted, sep="\n")

[[-1.14684361  0.05321626  1.1827419  -0.48443672]
 [ 1.4834781   1.12534856  0.43286956 -0.11057765]
 [ 1.10238056 -1.33273727 -0.06691798  0.39988253]]
[[-1.14684361 -0.48443672  0.05321626  1.1827419 ]
 [-0.11057765  0.43286956  1.12534856  1.4834781 ]
 [-1.33273727 -0.06691798  0.39988253  1.10238056]]
[[0 3 1 2]
 [3 2 1 0]
 [1 2 3 0]]
[[-1.14684361 -1.33273727 -0.06691798 -0.48443672]
 [ 1.10238056  0.05321626  0.43286956 -0.11057765]
 [ 1.4834781   1.12534856  1.1827419   0.39988253]]
[[0 2 2 0]
 [2 0 1 1]
 [1 1 0 2]]
[[-1.14684361 -0.48443672  0.05321626  1.1827419 ]
 [-0.11057765  0.43286956  1.12534856  1.4834781 ]
 [-1.33273727 -0.06691798  0.39988253  1.10238056]]
[[0 3 1 2]
 [3 2 1 0]
 [1 2 3 0]]


## Normalize array

In [234]:
rn_Normalized = (rn - rn_mean) / rn_std  # normalizing the array
rn_Normalized

array([[-1.56139622, -0.19038987,  1.10003476, -0.8046306 ],
       [ 1.44361031,  1.03446583,  0.24334439, -0.37751595],
       [ 1.00822607, -1.7737701 , -0.32763703,  0.20565841]])

In [235]:
rn_Normalized_mean = np.mean(rn_Normalized)  # mean of normalized array
rn_Normalized_std = np.std(rn_Normalized)  # standard deviation of normalized array
print(rn_Normalized_mean, rn_Normalized_std)

6.245004513516506e-17 0.9999999999999998
